name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
    - name: Assign new issues and pull requests to project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/orgs/Phalcode/projects/2'
        column_name: 'Todo Frontend'
